---
- name: Create root's .my.cnf config file (This allows you to login to mysql with cached credentials)
  template:
    src: ../templates/my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600
  become: yes

- name: Set root password in MariaDB
  mysql_user: login_password='' host={{ item }} check_implicit_admin=yes name='root' password='' state=present 
  with_items:
    - localhost
    - 127.0.0.1
    - ::1
  become: yes
  ignore_errors: TRUE
 
- name: Remove anonymous users from database
  mysql_user:
    name: ''
    host_all: yes
    state: absent
  become: yes

- name: Disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False
  become: yes
    
- name: Remove test database and access to it
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DROP DATABASE IF EXISTS test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False
  become: yes

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False
  become: yes

